create table
  public."AppointmentRecords" (
    id bigint generated by default as identity not null,
    owner_id uuid null,
    ticket_num text null,
    vaccine_sched_id bigint null,
    time time without time zone null,
    pet_id uuid null,
    status text null default 'uved'::text,
    constraint AppointmentRecords_pkey primary key (id),
    constraint AppointmentRecords_owner_id_fkey foreign key (owner_id) references "PetOwnerProfiles" (id) on update cascade on delete cascade,
    constraint AppointmentRecords_pet_id_fkey foreign key (pet_id) references "PetRecords" (id) on update cascade on delete cascade,
    constraint AppointmentRecords_vaccine_sched_id_fkey foreign key (vaccine_sched_id) references "VaccinationSchedule" (id) on update cascade on delete cascade
  ) tablespace pg_default;