create table
  public."VaccineInventory" (
    id bigint generated by default as identity not null,
    batch_number text not null,
    name text not null,
    stockin_date date not null,
    expiration_date date not null,
    original_qty integer not null,
    remaining_qty integer not null,
    status text not null,
    last_modified timestamp with time zone not null default now(),
    constraint vaccine_management_records_pkey primary key (id)
  ) tablespace pg_default;