create table public."AdminNotifications" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    message text not null,
    constraint AdminNotifications_pkey primary key (id)
) tablespace pg_default;