create table
  public."DistributedVaccines" (
    id bigint generated by default as identity not null,
    inventory_id bigint not null,
    date date null,
    num_vaccines integer null,
    barangay text null,
    constraint DistributedVaccines_pkey primary key (id),
    constraint DistributedVaccines_inventory_id_fkey foreign key (inventory_id) references "VaccineInventory" (id) on update cascade on delete cascade
  ) tablespace pg_default;