create table
  public."VaccinationRecords" (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    vax_sched_id bigint null,
    vaccine_id bigint null,
    pet_id uuid null,
    constraint VaccinationRecords_pkey primary key (id),
    constraint VaccinationRecords_pet_id_fkey foreign key (pet_id) references "PetRecords" (id) on update cascade on delete cascade,
    constraint VaccinationRecords_vaccine_id_fkey foreign key (vaccine_id) references "VaccineInventory" (id) on update cascade on delete cascade,
    constraint VaccinationRecords_vax_sched_id_fkey foreign key (vax_sched_id) references "VaccinationSchedule" (id) on update cascade on delete cascade
  ) tablespace pg_default;