import { supabase } from "@/utils/supabase";

//DELETED

// create table
//   public."VaccinatedPetRecords" (
//     id bigint generated by default as identity,
//     pet_id uuid not null,
//     date_vaccinated date null,
//     pet_specie character varying null,
//     constraint VaccinatedPetRecords_pkey primary key (id),
//     constraint VaccinatedPetRecords_pet_id_fkey foreign key (pet_id) references "PetRecords" (id) on update cascade on delete cascade,
//     constraint VaccinatedPetRecords_pet_specie_check check ((length((pet_specie)::text) < 10))
//   ) tablespace pg_default;

// export const fetchVaccinatedPets = async (barangay: string) => {
//   let query = supabase.from("VaccinatedPetRecords").select(`
//     id,
//     pet_id,
//     pet_specie,
//     date_vaccinated,
//     PetRecords!inner (owner_id, PetOwnerProfiles!inner (barangay))
//   `);

//   if (barangay !== "") {
//     query = query.eq("PetRecords.PetOwnerProfiles.barangay", barangay);
//   }

//   const response = await query;

//   if (response.error) {
//     console.error("Error fetching data:", response.error);
//     return;
//   }

//   const totalRecords: { [key: string]: number } = {};
//   const monthNames = [
//     "January",
//     "February",
//     "March",
//     "April",
//     "May",
//     "June",
//     "July",
//     "August",
//     "September",
//     "October",
//     "November",
//     "December",
//   ];
//   const currentYear = new Date().getFullYear();

//   response.data.forEach((record) => {
//     const recordDate = new Date(record.date_vaccinated);
//     if (recordDate.getFullYear() === currentYear) {
//       const month = monthNames[recordDate.getMonth()];
//       if (!totalRecords[month]) {
//         totalRecords[month] = 0;
//       }
//       totalRecords[month]++;
//     }
//   });

//   const filteredData = response.data.filter(
//     (record) => new Date(record.date_vaccinated).getFullYear() === currentYear
//   );

//   const totalCats = filteredData.filter(
//     (record) => record.pet_specie === "cat"
//   ).length;
//   const totalDogs = filteredData.filter(
//     (record) => record.pet_specie === "dog"
//   ).length;

//   return { totalRecords, totalCats, totalDogs };
// };
// export const fetchVaccinatedPetsAllBarangay = async () => {
//   try {
//     let query = supabase
//       .from("VaccinatedPetRecords")
//       .select(`*`, { count: "exact" });

//     const { data, error, status, count } = await query;

//     if (error) {
//       throw error;
//     }

//     return {
//       data: data,
//       count: count,
//       status: status,
//     };
//   } catch (error) {
//     console.error("Error fetching data:", error);
//     return null;
//   }
// };

export const fetchPetOwnerRegistered = async (barangay: string) => {
  let query = supabase.from("PetOwnerProfiles").select("*", { count: "exact" });

  if (barangay !== "") {
    query = query.eq("barangay", barangay);
  }

  const { data, error, count } = await query;

  if (error) {
    console.error("Error fetching data:", error);
    return;
  }

  return count;
};

export const fetchPetOwnersRegisteredAllBarangay = async () => {
  try {
    let query = supabase
      .from("PetOwnerProfiles")
      .select(`*`, { count: "exact" });

    const { data, error, status, count } = await query;

    if (error) {
      throw error;
    }

    return {
      data,
      count,
      status,
    };
  } catch (error) {
    console.error("Error fetching data:", error);
    return null;
  }
};
